version: "3"

services:

    ### Apache-PHP Web Server Container ##################################
    web:
        container_name: buzzvil-ads
        hostname: hostname-ads
        build:
            context: ./apache2
            dockerfile: Dockerfile
        privileged: true
        ports:
            - "8080:80"
        volumes:
            - ./workspace:/pub/development
            - ./logs/apache2:/var/log/apache2
            - ./logs/supervisor:/var/log/supervisor
        links:
            - mysql-master
            - mysql-master:database
            - mysql-slave
            - mysql-slave:database
            - redis
        depends_on:
            - mysql-slave

    ### MySQL Master Container #########################################
    mysql-master:
        container_name: buzzvil-mysql-master
        hostname: hostname-mysql-master
        restart: always
        build:
            context: ./mysql-master
            dockerfile: Dockerfile
            args:
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: buzzvil
                MYSQL_USER: buzzvil
                MYSQL_PASSWORD: buzzvil
        user: root
        privileged: true
        stdin_open: true
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ../resources:/var/lib/mysql-files/
        command: /usr/sbin/init
        networks:
            dock_net:
                ipv4_address: 172.16.0.10

    ### MySQL Slave Container #########################################
    mysql-slave:
        container_name: buzzvil-mysql-slave
        hostname: hostname-mysql-slave
        restart: always
        build:
            context: ./mysql-slave
            dockerfile: Dockerfile
            args:
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: buzzvil
                MYSQL_USER: buzzvil
                MYSQL_PASSWORD: buzzvil
        user: root
        privileged: true
        stdin_open: true
        tty: true
        ports:
            - "3307:3306"
        volumes:
            - ../resources:/var/lib/mysql-files/
        command: /usr/sbin/init
        networks:
            dock_net:
                ipv4_address: 172.16.0.11
        depends_on:
            - mysql-master
    
    ### Redis Container #########################################
    redis:
        image: redis:6.2.1-alpine
        container_name: buzzvil-redis
        hostname: hostname-redis
        ports:
            - 6379:6379

### Network setting #########################################
networks: 
  dock_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16