version: "3"

services:

    ### Apache-PHP Web Server Container ##################################
    web:
        container_name: buzzvil-ads
        hostname: hostname-ads
        build:
            context: ./apache2
            dockerfile: Dockerfile
        privileged: true
        ports:
            - "8080:80"
        volumes:
            - ./workspace:/pub/development
            - ./logs/apache2:/var/log/httpd
            - ./logs/supervisor:/var/log/supervisor
        networks:
            dock_net:
                ipv4_address: 172.16.0.10
        depends_on:
            - mysql-slave-2

    ### Redis Container #########################################
    redis:
        image: redis:6.2.1-alpine
        container_name: buzzvil-redis
        hostname: hostname-redis
        ports:
            - 6379:6379
        networks:
            dock_net:
                ipv4_address: 172.16.0.11

    ### MySQL Master Container #########################################
    mysql-master:
        container_name: buzzvil-mysql-master
        hostname: hostname-mysql-master
        restart: always
        build:
            context: ./mysql-master
            dockerfile: Dockerfile
            args:
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: buzzvil
                MYSQL_USER: buzzvil
                MYSQL_PASSWORD: buzzvil
        user: root
        privileged: true
        stdin_open: true
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ../resources:/var/lib/mysql-files/
        command: /usr/sbin/init
        networks:
            dock_net:
                ipv4_address: 172.16.0.12

    ### MySQL Slave-1 Container #########################################
    mysql-slave-1:
        container_name: buzzvil-mysql-slave-1
        hostname: hostname-mysql-slave-1
        restart: always
        build:
            context: ./mysql-slave-1
            dockerfile: Dockerfile
            args:
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: buzzvil
                MYSQL_USER: buzzvil
                MYSQL_PASSWORD: buzzvil
        user: root
        privileged: true
        stdin_open: true
        tty: true
        ports:
            - "3307:3306"
        volumes:
            - ../resources:/var/lib/mysql-files/
        command: /usr/sbin/init
        networks:
            dock_net:
                ipv4_address: 172.16.0.13
        depends_on:
            - mysql-master

    ### MySQL Slave-2 Container #########################################
    mysql-slave-2:
        container_name: buzzvil-mysql-slave-2
        hostname: hostname-mysql-slave-2
        restart: always
        build:
            context: ./mysql-slave-2
            dockerfile: Dockerfile
            args:
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: buzzvil
                MYSQL_USER: buzzvil
                MYSQL_PASSWORD: buzzvil
        user: root
        privileged: true
        stdin_open: true
        tty: true
        ports:
            - "3308:3306"
        volumes:
            - ../resources:/var/lib/mysql-files/
        command: /usr/sbin/init
        networks:
            dock_net:
                ipv4_address: 172.16.0.14
        depends_on:
            - mysql-slave-1

### Network setting #########################################
networks: 
  dock_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16